version: "3.7"

services:
  database: 
    image: postgres
    container_name: db_imov
    restart: always
    ports:
      - 5432:5432 
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=dbimov
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  api:
    build: ./backend
    container_name: api_imov
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes: 
      - ./backend:/usr/app
    network_mode: host
    depends_on: 
      - database
  app:
      build: ./frontend
      container_name: app_imov
      restart: always
      ports:
        - 3000:3000
      volumes: 
        - ./frontend:/usr/app
      network_mode: host
      depends_on: 
        - database
        - api
volumes: 
  pgdata:
    driver: local
