version: "3.7"

services:
  database: 
    image: postgres
    container_name: db_imobsis
    restart: always
    ports:
      - 5432:5432 
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=imobsis
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: api_imobsis
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes: 
      - .:/usr/app
    network_mode: host
    depends_on: 
      - database

volumes: 
  pgdata:
    driver: local
